# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f5da3fcb93477e87caed7af0b8640e3675b7a1d382c4f82dc822124425fda1137ad5641494351ad087bfcf0a1ac01292dbc4152d6e45e285968b2680c4845e1

test:
  secret_key_base: da0a0bbbbdd73f00ee67d4843f6dd329c1a050b73bceaef8464fd35406d9293cefd5fa222920c1bd2bee4a2293ae02dfa20b7d51a304af6866e85ea67b4ddcb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
